spring:
  application:
    name: consul-admin
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /
        healthCheckInterval: 5s
  ##默认后缀
  mvc:
    view:
      suffix: .html
  ##关闭thymeleaf缓存
  thymeleaf:
    cache: false
  ##ftl配置
  freemarker:
    ## 文件配置路径 template-loader-path: classpath:/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true


server:
  port: 8082
  session-timeout: 10
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8
