spring:
  application:
    name: gateway-https
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
server:
  ssl:
    # 在生成证书时键入的别名
    key-alias: certificatekey
    enabled: true
    # 证书密码，我设置的相同的
    key-password: 12979613
    # 证书，与application.yml统计目录下
    key-store: classpath:shfqkeystore.jks
    key-store-type: JKS
    key-store-provider: SUN
    # 证书存储密码，我设置的相同的
    key-store-password: 12979613
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG