spring:
  application:
    name: gateway-https
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
server:
  ssl:
    key-alias: certificatekey
    enabled: true
    key-password: 12979613
    key-store: classpath:shfqkeystore.jks
    key-store-type: JKS
    key-store-provider: SUN
    key-store-password: 12979613
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG