server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:  # http://localhost:8080/actuator/gateway/routes
      exposure:
        include: "*"

## ---- yml配置方式 ----
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: after_route
#        uri: http://baidu.com
#        predicates:
#        - After=2022-01-22T17:27:58.909+08:00[Asia/Shanghai]