server:
  port: 8081
spring:
  application:
    name: spring-cloud-gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:  # http://localhost:8080/actuator/gateway/routes
      exposure:
        include: "*"


## ---- yml配置方式 ----
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: host_route
#        uri: http://jd.com
#        predicates:
#        - Host=**.baidu.com:8080